POST http://localhost:8080/api/opinion
Content-Type: application/json

{
  "assetName": "SECO ETF",
  "assetType": "ETF",
  "amount": 100,
  "currency": "EUR",
  "reason": "I want exposure to the semiconductor sector because I believe demand for chips and AI infrastructure will continue to grow.",
  "riskLevel": "High",
  "investmentHorizon": "5 years",
  "exitPlan": "I will sell if the ETF drops below my risk tolerance or if the sector becomes overvalued."
}

###

GET http://localhost:8080/api/opinion/4e6ea353-d814-4511-a643-2a001de1d5a1