### Create investment decision
POST http://localhost:8080/api/opinion
Content-Type: application/json

{
  "assetName": "SECO ETF",
  "assetType": "ETF",
  "amount": 100,
  "currency": "EUR",
  "reason": "I want exposure to the semiconductor sector because I believe demand for chips and AI infrastructure will continue to grow.",
  "riskLevel": "High",
  "investmentHorizon": "5 years",
  "exitPlan": "I will sell if the ETF drops below my risk tolerance or if the sector becomes overvalued."
}

### Get all investment decisions
GET http://localhost:8080/api/opinion

### Get investment decision by ID
GET http://localhost:8080/api/opinion/PASTE_EXISTING_ID_HERE

### Update investment decision by ID
PUT http://localhost:8080/api/opinion/PASTE_EXISTING_ID_HERE
Content-Type: application/json

{
  "assetName": "Gold",
  "assetType": "Commodity",
  "amount": 250,
  "currency": "EUR",
  "reason": "Gold hedge.",
  "riskLevel": "",
  "investmentHorizon": "",
  "exitPlan": ""
}

### Delete investment decision by ID
DELETE http://localhost:8080/api/opinion/PASTE_EXISTING_ID_HERE

### Test not found response
GET http://localhost:8080/api/opinion/11111111-1111-1111-1111-111111111111